<?php

namespace RozzBundle\Repository;

/**
 * ApplicationSettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationSettingsRepository extends \Doctrine\ORM\EntityRepository
{
}
