<?php

namespace RozzBundle\Repository;

/**
 * CadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CadRepository extends \Doctrine\ORM\EntityRepository
{
}
