<?php

namespace RozzBundle\Repository;

/**
 * ConturRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConturRepository extends \Doctrine\ORM\EntityRepository
{
}
