<?php

namespace RozzBundle\Repository;
use RozzBundle\Entity\Holders;

/**
 * contractsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class contractsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllActiveAndHasNum_ByHolder(Holders $holder)
    {
        $now = new \DateTime('now');
        $qb = $this->createQueryBuilder('c');
        $qb->where('c.holder = :holder' )
            ->andWhere('c.expire >= :date')
            ->andWhere('c.num != :null')
            ->setParameter('holder', $holder)
            ->setParameter('date',$now)
            ->setParameter('null','')
        ;
        return $qb->getQuery()
            ->getResult();
    }
}
