<?php

namespace RozzBundle\Repository;

/**
 * docRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class docRepository extends \Doctrine\ORM\EntityRepository
{
}
