<?php

namespace RozzBundle\Repository;

/**
 * ExaminersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExaminersRepository extends \Doctrine\ORM\EntityRepository
{
}
