<?php

namespace RozzBundle\Repository;

/**
 * HoldersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HoldersRepository extends \Doctrine\ORM\EntityRepository
{
}
