<?php

namespace RozzBundle\Repository;

/**
 * katRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class katRepository extends \Doctrine\ORM\EntityRepository
{
}
