<?php

namespace RozzBundle\Repository;

/**
 * landsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class landsRepository extends \Doctrine\ORM\EntityRepository
{
}
