<?php

namespace RozzBundle\Repository;

/**
 * MayorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MayorsRepository extends \Doctrine\ORM\EntityRepository
{
}
