<?php

namespace RozzBundle\Repository;

/**
 * MestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MestRepository extends \Doctrine\ORM\EntityRepository
{
}
