<?php

namespace RozzBundle\Repository;

/**
 * NeighboursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NeighboursRepository extends \Doctrine\ORM\EntityRepository
{
}
