<?php

namespace RozzBundle\Repository;

/**
 * contractsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class newContractsRepository extends \Doctrine\ORM\EntityRepository
{
}
