<?php

namespace RozzBundle\Repository;

/**
 * ntpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ntpRepository extends \Doctrine\ORM\EntityRepository
{
}
