<?php

namespace RozzBundle\Repository;

/**
 * selectedLandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class selectedLandRepository extends \Doctrine\ORM\EntityRepository
{
}
