<?php

namespace RozzBundle\Repository;

/**
 * UsedAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsedAreaRepository extends \Doctrine\ORM\EntityRepository
{
}
