<?php

namespace RozzBundle\Repository;

/**
 * ZemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZemRepository extends \Doctrine\ORM\EntityRepository
{
}
